api:
  h2console:
    url:
      path: /users-ws/h2-console/**
  login:
    url:
      path: /users-ws/users/login
  registration:
    url:
      path: /users-ws/users
  users:
    actuator:
      url:
        path: /users-ws/actuator/*

  zuul:
    actuator:
      url:
        path: /actuator/*
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka
server:
  port: 8011
spring:
  application:
    name: zuul
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

auth:
  token:
    header:
      name: Authorization
      prefix: Bearer
